### PR TITLE
Script Caps lock to escape

### PR DESCRIPTION
**Pull request by jersearls**
I noticed in your readme you mentioned something about this.

If you want to totally disable caps lock, you may be able to still do something similar.

To get it working:

Create a script that line 19 of `install` will point to containing the following line:

```##set caps lock to escape
hidutil property --set '{"UserKeyMapping":[{"HIDKeyboardModifierMappingSrc":0x700000039,"HIDKeyboardModifierMappingDst":0x700000029}]}'
```

Simply running the command doesn't seem to persist after a reboot, so this method will allow for the changes to persist by running the script at login. 

Hope this helps, and if it isn't what you're looking for, then no worries!

### CODE REVIEW

**Comment by samjonester** [comment]
That's really cool! Lately, I've adopted the built in mac preferences option to map caps lock to escape:

image

I'm not sure if I want to switch from something that is an OS setting to a script run during log-in, but I do appreciate you taking the time to share :)

Also, I appreciate you giving me the prompt to better document _how_ I do the remapping, since my install script has languished without the need to actually _run_ it 🙈

**Comment by jersearls** [comment]
No problem! For me scripting it was just one less thing to think about, but thankfully you're right, it has been added to the UI. Just set up my tmate based on your blog post by the way, love it!

**Comment by samjonester** [comment]
Nice! Hopefully it works well for you. If you’d like to test it out, I’m sure we can find an excuse to pair on something sam@{you know where}

**Comment by jersearls** [comment]
Got it tested and working with Jason. Yes, very excited to pair with you, have so much to learn! 😄

**Pull request closed without merging**
